import { InteriorShell } from "@/components/site/interior-shell";
import { buildIntelligenceSnapshot } from "@/lib/intelligence/build-snapshot";
import { getIntelligenceSnapshot } from "@/server/intelligence/get-snapshot";

export const dynamic = "force-dynamic";

export default async function IntelligencePage() {
  let snapshot;
  try { snapshot = await getIntelligenceSnapshot(); } catch { snapshot = buildIntelligenceSnapshot([], 0); }
  return <InteriorShell eyebrow="09 / Intelligence" title="Lihat polanya, bukan orangnya." description="Snapshot 30 hari dari kategori risiko anonim, dipadukan dengan advisory keselamatan yang dikurasi." marker="ANON / AGGREGATE / CURRENT" fragments={[`${snapshot.observedScans || "<3"} OBSERVED`, `${snapshot.trends.length} TREND`, "NO CRAWLER"]} compact>
    <section data-reveal className="grid gap-px border border-line bg-line sm:grid-cols-3"><div className="bg-ink p-7 text-surface"><p className="font-mono text-xs uppercase text-surface/60">Pemeriksaan agregat</p><p className="mt-4 font-mono text-5xl font-semibold">{snapshot.observedScans || "—"}</p><p className="mt-2 text-xs text-surface/60">30 hari · minimum grup {snapshot.minimumGroupSize}</p></div><div className="bg-surface p-7"><p className="font-mono text-xs uppercase text-muted">Outcome terverifikasi</p><p className="mt-4 font-mono text-5xl font-semibold">{snapshot.verifiedOutcomes || "—"}</p><p className="mt-2 text-xs text-muted">Kategori saja, tanpa kronologi</p></div><div className="bg-ai-soft p-7"><p className="font-mono text-xs uppercase text-ai">URL network calls</p><p className="mt-4 font-mono text-5xl font-semibold">0</p><p className="mt-2 text-xs text-muted">AmanKlik tidak membuka URL input</p></div></section>

    <section data-reveal className="grid gap-8 border-b border-line py-14 lg:grid-cols-[0.35fr_0.65fr]"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-ai">Observed patterns</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em]">Sinyal yang sering muncul</h2><p className="mt-4 text-sm leading-7 text-muted">Persentase menunjukkan proporsi pemeriksaan dalam snapshot yang memuat pola tersebut, bukan tingkat kejadian penipuan di masyarakat.</p></div><div>{snapshot.trends.length ? <ol className="divide-y divide-line border-y border-line">{snapshot.trends.map((trend, index) => <li key={trend.id} className="grid gap-3 py-5 sm:grid-cols-[48px_1fr_90px] sm:items-center"><span className="font-mono text-xs text-muted">{String(index + 1).padStart(2, "0")}</span><div><strong>{trend.label}</strong><div className="mt-2 h-1.5 bg-line"><div className="h-full bg-ai" style={{ width: `${Math.min(trend.share, 100)}%` }} /></div></div><span className="font-mono text-right text-xl">{trend.share}%</span></li>)}</ol> : <div className="border border-dashed border-line p-8 text-sm leading-7 text-muted">Data belum melewati ambang anonimitas. Advisory kurasi tetap tersedia tanpa membuat tren palsu.</div>}</div></section>

    <section data-reveal className="py-14"><p className="font-mono text-xs uppercase tracking-[0.18em] text-ai">Curated advisories</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em]">Pola yang perlu dikenali sekarang</h2><div className="mt-8 grid gap-px border border-line bg-line md:grid-cols-2">{snapshot.advisories.map((advisory) => <article key={advisory.id} className="bg-surface p-6 sm:p-8"><div className="flex flex-wrap gap-2">{advisory.signalCategories.map((category) => <span key={category} className="rounded-full bg-ai-soft px-3 py-1 font-mono text-[10px] uppercase text-ai">{category.replaceAll("_", " ")}</span>)}</div><h3 className="mt-6 text-2xl font-semibold tracking-[-0.03em]">{advisory.title}</h3><p className="mt-3 text-sm leading-7 text-muted">{advisory.summary}</p><div className="mt-5 border-l-2 border-safe pl-4 text-sm leading-6"><strong>Langkah aman:</strong> {advisory.safeAction}</div><a className="mt-5 inline-flex text-xs font-semibold text-ai underline underline-offset-4" href={advisory.sourceUrl} target="_blank" rel="noreferrer">{advisory.sourceTitle}</a></article>)}</div></section>
    <footer className="border-t border-line py-8 text-sm leading-7 text-muted">{snapshot.privacyNote} Snapshot dibuat {new Date(snapshot.generatedAt).toLocaleString("id-ID")}.</footer>
  </InteriorShell>;
}
