import type { AffectedAsset, IncidentType, ResponseStep } from "@/lib/response/types";

const IASC = "https://iasc.ojk.go.id/";
const BI_APK = "https://www.bi.go.id/id/publikasi/ruang-media/cerita-bi/Pages/telanjur-klik-apk-penipuan.aspx";
const OJK_SECURITY = "https://www.ojk.go.id/id/Fungsi-Utama/ITSK/Informasi-IAKD/Digital-Financial-Literacy/Documents/2.%20Proteksi%20Diri%20dari%20Kejahatan%20Digital.pdf";
const OJK_IDEB = "https://idebku.ojk.go.id/";

export const OFFICIAL_SOURCE_HOSTS = new Set([
  "iasc.ojk.go.id",
  "www.bi.go.id",
  "www.ojk.go.id",
  "idebku.ojk.go.id",
]);

export const INCIDENT_LABELS: Record<IncidentType, string> = {
  money_transferred: "Uang sudah terkirim",
  unauthorized_transaction: "Ada transaksi yang tidak saya kenal",
  credential_or_card_shared: "OTP, PIN, kata sandi, atau data kartu sudah dibagikan",
  suspicious_app_installed: "Sudah memasang APK atau aplikasi dari chat",
  account_or_number_lost: "Akun atau nomor HP sudah diambil alih",
  identity_data_shared: "KTP, selfie, atau data pribadi sudah dibagikan",
  link_or_qr_opened: "Sudah membuka tautan atau memindai QR, tapi belum yakin dampaknya",
  goods_released_fake_payment: "Barang sudah diserahkan karena bukti bayar",
  unsure: "Saya tidak yakin apa yang sudah terjadi",
};

export const AFFECTED_ASSET_LABELS: Record<AffectedAsset, string> = {
  bank_or_wallet: "Bank, kartu, atau e-wallet",
  email: "Email utama",
  whatsapp: "WhatsApp",
  marketplace: "Marketplace",
  social_media: "Media sosial",
  phone_number: "Nomor HP atau SIM",
  device: "HP atau komputer",
};

export const INCIDENT_ASSET_OPTIONS: Record<IncidentType, AffectedAsset[]> = {
  money_transferred: ["bank_or_wallet", "marketplace"],
  unauthorized_transaction: ["bank_or_wallet", "marketplace"],
  credential_or_card_shared: [
    "bank_or_wallet",
    "email",
    "whatsapp",
    "marketplace",
    "social_media",
    "phone_number",
  ],
  suspicious_app_installed: ["device", "bank_or_wallet", "email", "whatsapp", "phone_number"],
  account_or_number_lost: [
    "bank_or_wallet",
    "email",
    "whatsapp",
    "marketplace",
    "social_media",
    "phone_number",
    "device",
  ],
  identity_data_shared: [],
  link_or_qr_opened: ["bank_or_wallet", "email", "marketplace", "social_media", "device"],
  goods_released_fake_payment: ["bank_or_wallet", "marketplace"],
  unsure: [
    "bank_or_wallet",
    "email",
    "whatsapp",
    "marketplace",
    "social_media",
    "phone_number",
    "device",
  ],
};

export function affectedAssetsForIncidents(incidents: IncidentType[]): AffectedAsset[] {
  const relevantAssets = new Set(incidents.flatMap((incident) => INCIDENT_ASSET_OPTIONS[incident] ?? []));

  return (Object.keys(AFFECTED_ASSET_LABELS) as AffectedAsset[])
    .filter((asset) => relevantAssets.has(asset));
}

const ACCOUNT_OR_DEVICE_INCIDENTS: IncidentType[] = [
  "credential_or_card_shared",
  "account_or_number_lost",
];

export const RESPONSE_CATALOG: ResponseStep[] = [
  {
    id: "disconnect-suspicious-app",
    incidentTypes: ["suspicious_app_installed"],
    urgency: "immediate",
    order: 1,
    title: "Matikan koneksi internet perangkat itu",
    body: "Aktifkan mode pesawat lalu matikan Wi-Fi. Jangan membuka mobile banking, email, atau akun penting dari perangkat tersebut sebelum langkah pengamanan selesai.",
    sourceTitle: "Telanjur klik APK penipuan | Bank Indonesia",
    sourceUrl: BI_APK,
  },
  {
    id: "remove-suspicious-app",
    incidentTypes: ["suspicious_app_installed"],
    urgency: "immediate",
    order: 5,
    title: "Hapus aplikasi dan cabut izin berbahaya",
    body: "Copot aplikasi yang baru dipasang. Periksa izin Aksesibilitas, administrator perangkat, SMS, notifikasi, dan instalasi aplikasi tidak dikenal; cabut izin yang tidak kamu kenali.",
    sourceTitle: "Telanjur klik APK penipuan | Bank Indonesia",
    sourceUrl: BI_APK,
  },
  {
    id: "secure-from-clean-device",
    incidentTypes: ["suspicious_app_installed"],
    urgency: "immediate",
    order: 8,
    title: "Amankan akun dari perangkat lain yang tepercaya",
    body: "Dari perangkat yang aman, hubungi bank atau e-wallet melalui aplikasi, nomor, atau situs resminya. Ganti kata sandi akun utama, mulai dari email. Jangan memakai tautan atau nomor dari chat tersebut.",
    sourceTitle: "Telanjur klik APK penipuan | Bank Indonesia",
    sourceUrl: BI_APK,
  },
  {
    id: "verify-real-balance",
    incidentTypes: ["goods_released_fake_payment"],
    urgency: "immediate",
    order: 9,
    title: "Periksa saldo dan mutasi, bukan tangkapan layar",
    body: "Buka aplikasi bank atau e-wallet sendiri. Status pada chat, email, struk, atau tangkapan layar tidak membuktikan uang sudah masuk.",
  },
  {
    id: "contact-financial-provider",
    incidentTypes: ["money_transferred", "unauthorized_transaction"],
    urgency: "immediate",
    order: 10,
    title: "Hubungi bank atau e-wallet sekarang",
    body: "Pakai nomor di aplikasi, kartu, atau situs yang kamu ketik sendiri. Minta pengamanan akses dan jelaskan waktu, jumlah, serta rekening tujuan atau transaksi yang tidak dikenal. Pemblokiran atau pengembalian dana tidak bisa dijamin.",
    sourceTitle: "Indonesia Anti-Scam Centre | OJK",
    sourceUrl: IASC,
  },
  {
    id: "stop-sharing-identity",
    incidentTypes: ["identity_data_shared"],
    urgency: "immediate",
    order: 10,
    title: "Hentikan pengiriman data tambahan",
    body: "Jangan kirim foto identitas, selfie, tanda tangan, kode, atau dokumen tambahan. Jangan membayar pihak yang mengaku bisa menghapus atau memulihkan data.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "close-link-and-stop",
    incidentTypes: ["link_or_qr_opened"],
    urgency: "immediate",
    order: 10,
    title: "Tutup halaman dan jangan lanjutkan interaksi",
    body: "Membuka tautan atau memindai QR saja belum membuktikan akun atau perangkat sudah diambil alih. Jangan mengisi data, menyetujui izin, mengunduh file, atau melakukan pembayaran dari halaman itu.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "pause-when-unsure",
    incidentTypes: ["unsure"],
    urgency: "immediate",
    order: 10,
    title: "Hentikan chat, pembayaran, dan persetujuan baru",
    body: "Jangan kirim apa pun lagi sampai situasinya jelas. Tutup pesan atau panggilan dan jangan percaya pihak yang menawarkan pemulihan berbayar.",
  },
  {
    id: "secure-financial-asset",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["bank_or_wallet"],
    urgency: "immediate",
    order: 11,
    title: "Kunci akses bank, kartu, atau e-wallet",
    body: "Hubungi penyedia lewat aplikasi atau situs resmi yang kamu cari sendiri. Blokir akses atau kartu yang terdampak, ubah kata sandi atau PIN dari perangkat aman, lalu periksa transaksi terakhir.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "secure-phone-number",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["phone_number"],
    urgency: "immediate",
    order: 11,
    title: "Hubungi operator seluler dan amankan SIM",
    body: "Gunakan gerai, aplikasi, atau nomor resmi operator untuk memblokir atau memulihkan nomor. Setelah itu, periksa akun yang memakai SMS atau nomor tersebut untuk pemulihan.",
  },
  {
    id: "report-iasc-transfer",
    incidentTypes: ["money_transferred"],
    urgency: "immediate",
    order: 12,
    title: "Laporkan segera melalui portal resmi IASC",
    body: "Buka hanya iasc.ojk.go.id. Siapkan bukti transfer, rekening sumber dan tujuan, waktu, jumlah, urutan kejadian, serta bukti komunikasi. Simpan nomor laporan; pelaporan tidak menjamin dana kembali.",
    sourceTitle: "Portal resmi Indonesia Anti-Scam Centre",
    sourceUrl: IASC,
  },
  {
    id: "secure-root-email",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["email"],
    urgency: "immediate",
    order: 12,
    title: "Pulihkan email utama lebih dulu",
    body: "Masuk lewat aplikasi atau situs resmi, ubah kata sandi, keluarkan perangkat yang tidak dikenal, lalu periksa email pemulihan, nomor pemulihan, dan aturan penerusan pesan yang berubah.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "secure-messaging-account",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["whatsapp"],
    urgency: "immediate",
    order: 13,
    title: "Pulihkan WhatsApp dan beri tahu kontak",
    body: "Gunakan proses pemulihan di aplikasi resmi. Keluar dari perangkat tertaut yang tidak dikenal dan beri tahu kontak melalui nomor atau aplikasi lain agar mengabaikan permintaan uang atau kode.",
  },
  {
    id: "secure-marketplace-account",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["marketplace"],
    urgency: "immediate",
    order: 13,
    title: "Kunci akun marketplace dan periksa pesanan",
    body: "Gunakan pusat bantuan resmi marketplace. Ubah kata sandi, keluarkan perangkat yang tidak dikenal, dan periksa pesanan, alamat, cara pembayaran, saldo, serta percakapan penjual-pembeli.",
  },
  {
    id: "secure-social-account",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["social_media"],
    urgency: "immediate",
    order: 13,
    title: "Pulihkan media sosial dan cabut sesi asing",
    body: "Gunakan pusat bantuan resmi aplikasi, ubah kata sandi, periksa email dan nomor pemulihan, lalu beri tahu kontak jika akun sempat mengirim pesan yang bukan darimu.",
  },
  {
    id: "secure-device-access",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    affectedAssets: ["device"],
    urgency: "immediate",
    order: 13,
    title: "Amankan perangkat dari perangkat lain",
    body: "Gunakan fitur resmi pencarian perangkat untuk mengunci perangkat yang hilang jika tersedia. Dari perangkat tepercaya, amankan email utama dan akun yang masih tersambung.",
  },
  {
    id: "secure-account-fallback",
    incidentTypes: ACCOUNT_OR_DEVICE_INCIDENTS,
    requiresNoAffectedAsset: true,
    urgency: "immediate",
    order: 14,
    title: "Amankan akun yang paling penting lebih dulu",
    body: "Mulai dari email utama, lalu akun keuangan dan komunikasi. Buka aplikasi atau situs resmi sendiri, ubah kata sandi, keluarkan perangkat yang tidak dikenal, dan periksa cara pemulihan akun.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "stop-goods-handover",
    incidentTypes: ["goods_released_fake_payment"],
    urgency: "immediate",
    order: 15,
    title: "Hentikan penyerahan atau pengiriman berikutnya",
    body: "Jika barang masih dapat ditahan secara aman, jangan serahkan berdasarkan bukti bayar. Jangan konfrontasi pelaku atau mengambil risiko fisik untuk mengejar barang.",
  },
  {
    id: "block-unauthorized-access",
    incidentTypes: ["unauthorized_transaction"],
    urgency: "immediate",
    order: 15,
    title: "Blokir akses atau alat pembayaran yang terdampak",
    body: "Ikuti petunjuk resmi penyedia untuk memblokir kartu, akun, atau perangkat yang terhubung. Ubah kata sandi atau PIN dari perangkat tepercaya dan jangan menyetujui notifikasi atau OTP baru.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "preserve-identity-evidence",
    incidentTypes: ["identity_data_shared"],
    urgency: "immediate",
    order: 20,
    title: "Simpan bukti siapa menerima data dan kapan",
    body: "Simpan chat, akun, nomor, tautan, waktu, dan jenis dokumen yang terkirim. Jangan menyebarkan ulang foto identitas atau mengunggahnya ke AmanKlik.",
  },
  {
    id: "classify-link-impact",
    incidentTypes: ["link_or_qr_opened"],
    urgency: "immediate",
    order: 20,
    title: "Ingat tindakan setelah halaman terbuka",
    body: "Jika kamu mengisi OTP, PIN, kata sandi, atau data kartu, pilih juga pilihan tentang data rahasia. Jika memasang APK atau memberi izin aplikasi, pilih juga pilihan tentang aplikasi agar langkah pengamanannya muncul.",
  },
  {
    id: "verify-official-activity",
    incidentTypes: ["unsure"],
    urgency: "immediate",
    order: 20,
    title: "Periksa dari aplikasi resmi yang kamu buka sendiri",
    body: "Lihat mutasi rekening, perangkat yang masuk ke akun, perubahan kata sandi, dan pemberitahuan keamanan. Jangan memakai tombol atau nomor dari pesan mencurigakan.",
  },
  {
    id: "revoke-sessions",
    incidentTypes: ["credential_or_card_shared"],
    urgency: "immediate",
    order: 20,
    title: "Ganti rahasia dan keluarkan sesi asing",
    body: "Dari perangkat tepercaya, ganti kata sandi atau PIN yang terdampak. Jangan pakai ulang kata sandi lama, keluarkan perangkat yang tidak dikenal, dan aktifkan verifikasi dua langkah jika tersedia.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "document-unauthorized-transaction",
    incidentTypes: ["unauthorized_transaction"],
    urgency: "immediate",
    order: 25,
    title: "Catat transaksi tanpa mengubah bukti",
    body: "Simpan waktu, jumlah, nama merchant atau rekening tujuan, notifikasi, dan nomor pengaduan penyedia. Jangan menghapus percakapan atau notifikasi terkait.",
  },
  {
    id: "contact-marketplace-or-logistics",
    incidentTypes: ["goods_released_fake_payment"],
    urgency: "immediate",
    order: 25,
    title: "Hubungi marketplace atau layanan kirim dari aplikasi resminya",
    body: "Jika transaksi atau pengiriman melewati aplikasi, minta bantuan penahanan sesuai petunjuk mereka. Berikan nomor pesanan atau resi hanya melalui aplikasi atau situs resmi.",
  },
  {
    id: "contain-account-takeover",
    incidentTypes: ["account_or_number_lost"],
    urgency: "immediate",
    order: 20,
    title: "Jangan bernegosiasi melalui akun yang diambil alih",
    body: "Jangan mengirim kode atau uang kepada orang yang menguasai akun. Simpan bukti perubahan akses dan gunakan proses pemulihan resmi dari perangkat tepercaya.",
  },
  {
    id: "review-recovery-methods",
    incidentTypes: ["credential_or_card_shared"],
    urgency: "immediate",
    order: 30,
    title: "Periksa email, nomor, dan perangkat pemulihan",
    body: "Hapus cara pemulihan dan perangkat yang tidak dikenal. Jika data kartu ikut dibagikan, hubungi penerbit kartu melalui nomor atau aplikasi resminya untuk pengamanan atau penggantian.",
    sourceTitle: "Proteksi diri dari kejahatan digital | OJK",
    sourceUrl: OJK_SECURITY,
  },
  {
    id: "warn-after-account-takeover",
    incidentTypes: ["account_or_number_lost"],
    urgency: "immediate",
    order: 30,
    title: "Peringatkan kontak melalui nomor atau aplikasi lain",
    body: "Beri tahu orang terdekat bahwa akun atau nomor sedang diambil alih agar mereka mengabaikan permintaan uang, kode, tautan, atau perubahan rekening.",
  },
  {
    id: "inspect-downloads-and-permissions",
    incidentTypes: ["link_or_qr_opened"],
    urgency: "immediate",
    order: 30,
    title: "Periksa unduhan dan izin yang baru diberikan",
    body: "Periksa file unduhan, aplikasi baru, ekstensi browser, notifikasi situs, dan izin perangkat. Jangan membuka file mencurigakan; bila APK terpasang, ikuti jalur pengamanan aplikasi.",
  },
  {
    id: "check-ideb",
    incidentTypes: ["identity_data_shared"],
    urgency: "immediate",
    order: 30,
    title: "Periksa iDeb SLIK secara berkala",
    body: "Gunakan iDebKu OJK untuk melihat informasi debitur atas identitasmu. Hasil yang tidak dikenal perlu dikonfirmasi kepada lembaga terkait dan didokumentasikan.",
    sourceTitle: "iDebKu | OJK",
    sourceUrl: OJK_IDEB,
  },
  {
    id: "ask-trusted-person",
    incidentTypes: ["unsure"],
    urgency: "immediate",
    order: 30,
    title: "Minta satu orang tepercaya ikut memeriksa",
    body: "Tunjukkan situasinya tanpa membagikan OTP, PIN, kata sandi, atau foto identitas. Untuk akun tertentu, hubungi penyedia melalui aplikasi, nomor, atau situs resmi yang kamu cari sendiri.",
  },
  {
    id: "file-police-report",
    incidentTypes: ["money_transferred"],
    urgency: "immediate",
    order: 30,
    title: "Buat Laporan Polisi",
    body: "Laporan IASC tidak menggantikan proses hukum. Bawa identitas, bukti transaksi, urutan kejadian, dan bukti komunikasi ke kantor polisi terdekat; simpan nomor laporannya.",
    sourceTitle: "Alur pelaporan korban penipuan | IASC OJK",
    sourceUrl: IASC,
  },
  {
    id: "preserve-evidence",
    incidentTypes: [
      "money_transferred",
      "unauthorized_transaction",
      "credential_or_card_shared",
      "suspicious_app_installed",
      "account_or_number_lost",
      "identity_data_shared",
      "goods_released_fake_payment",
    ],
    urgency: "soon",
    order: 100,
    title: "Satukan bukti dan urutan kejadian",
    body: "Simpan tangkapan layar, nomor atau akun pengirim, waktu, transaksi, nomor pesanan atau resi, nama aplikasi, dan nomor laporan. Pertahankan file asli dan jangan unggah data rahasia ke AmanKlik.",
    sourceTitle: "Bukti yang dibutuhkan untuk laporan | IASC OJK",
    sourceUrl: IASC,
  },
  {
    id: "report-iasc-unauthorized",
    incidentTypes: ["unauthorized_transaction"],
    urgency: "soon",
    order: 105,
    title: "Jika terkait penipuan, laporkan juga ke IASC",
    body: "Gunakan hanya iasc.ojk.go.id dan tetap buat Laporan Polisi untuk proses hukum. Waspadai situs atau pihak yang mengaku sebagai jasa pemulihan dana.",
    sourceTitle: "Portal resmi Indonesia Anti-Scam Centre",
    sourceUrl: IASC,
  },
  {
    id: "review-account-activity",
    incidentTypes: ["credential_or_card_shared", "account_or_number_lost", "suspicious_app_installed", "link_or_qr_opened"],
    urgency: "soon",
    order: 110,
    title: "Periksa perubahan dan aktivitas akun",
    body: "Periksa transaksi, perangkat, sesi, email atau nomor pemulihan, aturan penerusan email, pesanan, dan pesan yang tidak kamu kenali. Laporkan perubahan ke penyedia resmi.",
  },
  {
    id: "consider-device-reset",
    incidentTypes: ["suspicious_app_installed"],
    urgency: "soon",
    order: 115,
    title: "Pertimbangkan pemeriksaan teknis atau reset perangkat",
    body: "Jika masih ada gejala, minta bantuan teknis tepercaya. Cadangkan hanya data penting sebelum reset pabrik; AmanKlik tidak dapat memastikan malware sudah hilang.",
    sourceTitle: "Telanjur klik APK penipuan | Bank Indonesia",
    sourceUrl: BI_APK,
  },
  {
    id: "report-confirmed-misuse",
    incidentTypes: ["identity_data_shared", "goods_released_fake_payment"],
    urgency: "soon",
    order: 120,
    title: "Laporkan bila sudah ada kerugian atau penyalahgunaan",
    body: "Jika muncul pinjaman, akun, transaksi, atau kehilangan barang yang tidak sah, hubungi lembaga atau platform terkait lalu buat Laporan Polisi dengan bukti yang tersimpan.",
  },
  {
    id: "monitor-follow-up",
    incidentTypes: [
      "money_transferred",
      "unauthorized_transaction",
      "credential_or_card_shared",
      "suspicious_app_installed",
      "account_or_number_lost",
      "identity_data_shared",
      "link_or_qr_opened",
      "goods_released_fake_payment",
      "unsure",
    ],
    urgency: "monitor",
    order: 200,
    title: "Waspadai serangan lanjutan dan jasa pemulihan palsu",
    body: "Pihak yang sama dapat kembali mengaku sebagai petugas, polisi, IASC, kurir, atau jasa pemulihan. Jangan membayar biaya pemulihan. Periksa setiap kontak melalui aplikasi, nomor, atau situs resmi yang kamu cari sendiri.",
  },
];
